[package]
name = "iceberg-rs"
version = "0.1.1-beta.0"
authors = ["Oliver Daff <oliverdaff@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "An implementation of Apache Iceberg in Rust"
homepage = "https://github.com/oliverdaff/iceberg-rs"
repository = "https://github.com/oliverdaff/iceberg-rs"
keywords = ["iceberg", "analytics", "data"]
categories = ["database", "filesystem"]
include = ["src/**/*.rs", "crates-io.md", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
readme = "crates-io.md"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
regex = "1.5.5"
lazy_static = "1.4.0"
avro-rs = { git = "https://github.com/oliverdaff/avro-rs", branch = "feat/metadata" }
serde_repr = "0.1"
num-bigint = "0.4.3"
anyhow = "1.0.57"
chrono = { version = "0.4.19", features = ["serde"] }

[dev-dependencies]
proptest = "1.0"
